### ISSUE TITLE
Prepare release?

### ISSUE THREAD

**Issue by mhvk** [liberfa/pyerfa#23]
I think we're quite close to releasing... To do
- [X] Set up authors (#21)
- [X] Set up version and document it (see #30)
- [X] Decide whether to use `setuptools_scm` for version number. see #28. [yes]
- [X] Expose `liberfa` version? I.e., port https://github.com/astropy/astropy/pull/9324; see #28 [yes]
- [X] ~Document the two C routines that are not part of `liberfa` - `pav2pv` and `pv2pav` (I've tried to get them up to SOFA, and probably should send a reminder).~ Remove the two extra routines, since we should not add stuff not in SOFA, and SOFA is unlikely to need it (could not find a single place where they would be useful). see #32.
- [X] Create change-log. See #34 
- [X] Add minimal usage instructions, which make distinction between ufunc and python wrapper. see #33
- [X] Check with Debian/redhat/conda, that we're making things easy enough (cc @olebole, @sergiopasra)
- [X] Document how to build with system `liberfa` library. See #28
- [X] Set up auto-release pipeline (#8; see #27)

@avalentino, @astrofrog - am I missing anything? If so, just edit this comment and add items.

**Comment by avalentino** [comment]
I don't see any other blocking issue.
Maybe it could be useful to have a beta release just to be able to make an upload on pypi.

**Comment by sergiopasra** [comment]
To package pyerfa in Fedora, it would be nice to support building with an external `erfa` library, just like `astropy` does. I have tried to had the following section in setup.cfg, but it doesn't work. Options are not recognized

```
[build]
use_system_libraries=1
use_system_erfa=1
```
```
error: error in setup.cfg: command 'build' has no such option 'use_system_erfa'
```

**Comment by mhvk** [comment]
Right now, it is done like in `astropy`, by setting an environment variable `PYERFA_USE_SYSTEM_LIBERFA=1`. But I like the approach of a change in `setup.cfg` - just need to find out how to access those settings in the actual build process...

**Comment by sergiopasra** [comment]
Well, for me setting an environment variable it's actually better. I will try to build it

**Comment by mhvk** [comment]
OK, obviously we should *document* this! added on top.

**Comment by olebole** [comment]
For an explanation: when built automatically, it is for a long-term better to have an environment variable or such. This can just be set in the build. In contrast, setting it in `setup.cfg` needs to patch that file before the build, which is done by the `patch` tool, or similar, in automated builds.  The latter needs a constant re-adjustment when the surrounding lines change, which complicates long-term maintainance.
I didn't check this yet, but I would just trust @sergiopasra here. Our requirements are not so different here :smiley:

**Comment by astrofrog** [comment]
@mhvk - I added to your list to set up auto-releasing. I can try and start setting that up now.

**Comment by astrofrog** [comment]
Do we want a changelog?

**Comment by mhvk** [comment]
> Do we want a changelog?

Yes, I think so. E.g., some of the wrappers right now do exactly nothing but call the ufunc (those that do not check warnings/errors), and we may at some point just remove those. 

And I guess we should at least have the logic between version numbers documented.  Added both on top.

For the auto-releasing, does that happen when we push a tag or make a github release?

**Comment by mhvk** [comment]
Never mind the question about auto-releasing - you already answered that in #27!

**Comment by mhvk** [comment]
Documentation of `PYERFA_USE_SYSTEM_LIBERFA` in #28

**Comment by astrofrog** [comment]
We now have the auto-releasing set up - and I've added the PyPI upload token to Azure Pipelines, so in principle it should work. Sometimes there are issues for the first release due to e.g. a typo in the Azure config and so on, so I'm happy to be on standby when one of you does the release in case anything goes wrong.

**Comment by astrofrog** [comment]
I'm going to be unavailable over the next couple of months, but @Cadair should have access to the Azure Pipelines set-up and can help with any issues relating to the auto-releasing. If anyone else wants to be added to the Azure Pipelines set-up, send me an email (to thomas.robitaille@gmail.com) to let me know what email address you use for your Azure account.

**Comment by mhvk** [comment]
OK, the release worked! Thanks, @astrofrog, for setting that part up.  Of course, I immediately noticed some small problems, but that's for a new issue... For now, this is done :fireworks:, and next is to adjust the astropy PR appropriately.

**Comment by astrofrog** [comment]
Pfew I'm glad the auto-release worked! :sweat_smile:
