### ISSUE TITLE
Post-1.7.0 release nits

### ISSUE THREAD

**Issue by mhvk** [liberfa/pyerfa#35]
- [x] Authors on pypi is still "the astropy developers", as is the e-mail. Fix in #43.
- [ ] A logo would still be nice (#26)
- [x] Should also publish to Zenodo;
- [x] Add zenodo badge; see #44
- [x] Might want to have travis badge; fix in #43.
- [x]  Also a readthedocs badge? Fix in #43.
- [x] Add link to readthedocs documentation in `README.rst` (and don't expose it in docs...); fix by adding a badge in #43

**Comment by mhvk** [comment]
@eteq or @astrofrog - could you enable third-party access so we can have pyerfa on zenodo? (I'm happy to do the actual linking, but it needs the access...)

**Comment by astrofrog** [comment]
I wasn't sure what was meant by 3rd party access but I've now made all PyERFA maintainers also be admins for the repo instead of just maintainers.

**Comment by mhvk** [comment]
Yes, it is! Now set up to automatically be stored on zenodo once another release is made. The changes above may be good enough to warrant an 1.7.0.1...

**Comment by mhvk** [comment]
Actually, turns out it is triggered by publishing on github, which I hadn't done yet (just had the tag), so just published 1.7.0 to be done with it. And #44 for adding the tag, so people have a DOI to cite.

**Comment by mhvk** [comment]
closing since this is done except for making a pyerfa badge, which already has its own issue
